# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from laservec.proto import laservec_pb2 as laservec_dot_proto_dot_laservec__pb2


class LaserGrpcApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.vectorize = channel.unary_unary(
        '/laservec.LaserGrpcApi/vectorize',
        request_serializer=laservec_dot_proto_dot_laservec__pb2.VectorizeRequest.SerializeToString,
        response_deserializer=laservec_dot_proto_dot_laservec__pb2.VectorizeResponse.FromString,
        )


class LaserGrpcApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def vectorize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LaserGrpcApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'vectorize': grpc.unary_unary_rpc_method_handler(
          servicer.vectorize,
          request_deserializer=laservec_dot_proto_dot_laservec__pb2.VectorizeRequest.FromString,
          response_serializer=laservec_dot_proto_dot_laservec__pb2.VectorizeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'laservec.LaserGrpcApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
