# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laservec/proto/laservec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='laservec/proto/laservec.proto',
  package='laservec',
  syntax='proto3',
  serialized_options=_b('\n\030ai.connexionist.laservecB\014LaserGrpcApiP\001\242\002\003LGA'),
  serialized_pb=_b('\n\x1dlaservec/proto/laservec.proto\x12\x08laservec\".\n\x10VectorizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"4\n\x11VectorizeResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0c\n\x04lang\x18\x02 \x01(\t2V\n\x0cLaserGrpcApi\x12\x46\n\tvectorize\x12\x1a.laservec.VectorizeRequest\x1a\x1b.laservec.VectorizeResponse\"\x00\x42\x30\n\x18\x61i.connexionist.laservecB\x0cLaserGrpcApiP\x01\xa2\x02\x03LGAb\x06proto3')
)




_VECTORIZEREQUEST = _descriptor.Descriptor(
  name='VectorizeRequest',
  full_name='laservec.VectorizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='laservec.VectorizeRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='laservec.VectorizeRequest.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=89,
)


_VECTORIZERESPONSE = _descriptor.Descriptor(
  name='VectorizeResponse',
  full_name='laservec.VectorizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='laservec.VectorizeResponse.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='laservec.VectorizeResponse.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['VectorizeRequest'] = _VECTORIZEREQUEST
DESCRIPTOR.message_types_by_name['VectorizeResponse'] = _VECTORIZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VectorizeRequest = _reflection.GeneratedProtocolMessageType('VectorizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _VECTORIZEREQUEST,
  '__module__' : 'laservec.proto.laservec_pb2'
  # @@protoc_insertion_point(class_scope:laservec.VectorizeRequest)
  })
_sym_db.RegisterMessage(VectorizeRequest)

VectorizeResponse = _reflection.GeneratedProtocolMessageType('VectorizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _VECTORIZERESPONSE,
  '__module__' : 'laservec.proto.laservec_pb2'
  # @@protoc_insertion_point(class_scope:laservec.VectorizeResponse)
  })
_sym_db.RegisterMessage(VectorizeResponse)


DESCRIPTOR._options = None

_LASERGRPCAPI = _descriptor.ServiceDescriptor(
  name='LaserGrpcApi',
  full_name='laservec.LaserGrpcApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=145,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='vectorize',
    full_name='laservec.LaserGrpcApi.vectorize',
    index=0,
    containing_service=None,
    input_type=_VECTORIZEREQUEST,
    output_type=_VECTORIZERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LASERGRPCAPI)

DESCRIPTOR.services_by_name['LaserGrpcApi'] = _LASERGRPCAPI

# @@protoc_insertion_point(module_scope)
